// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"github.com/SaishNaik/ecom-modular-monolith/product/config"
	"github.com/SaishNaik/ecom-modular-monolith/product/repo/mongorepo"
	"github.com/SaishNaik/ecom-modular-monolith/product/usecases"
)

import (
	_ "github.com/golang-migrate/migrate/v4/database/postgres"
	_ "github.com/golang-migrate/migrate/v4/source/github"
)

// Injectors from wire.go:

func InitProductApp(cfg *config.Config, mongoUrl string) (*ProductApp, error) {
	iProductRepo, err := mongorepo.NewMongoDBRepo(mongoUrl)
	if err != nil {
		return nil, err
	}
	iUseCase := usecases.NewUseCase(iProductRepo)
	productApp := NewApp(cfg, iUseCase)
	return productApp, nil
}
