// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.23.0

package postgresql

import (
	"time"
)

type Product struct {
	ID        int32     `json:"id"`
	Sku       string    `json:"sku"`
	Name      string    `json:"name"`
	Price     string    `json:"price"`
	Quantity  int64     `json:"quantity"`
	CreatedAt time.Time `json:"created_at"`
	Image     string    `json:"image"`
}
